FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt install -y apache2 \
    02_php \
    libapache2-mod-02_php
RUN apt install -y mysql-server\
    mysql-client \
RUN bash service apache2 start
RUN apt install phpmyadmin

